// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Pipeline lifecycle stages surfaced to the UI.
enum PipelineStage {
  idle,
  listening,
  processing,
  speaking,
  error,
}

class StatusUpdate {
  StatusUpdate({
    required this.stage,
    this.message,
  });

  PipelineStage stage;

  String? message;

  Object encode() {
    return <Object?>[
      stage,
      message,
    ];
  }

  static StatusUpdate decode(Object result) {
    result as List<Object?>;
    return StatusUpdate(
      stage: result[0]! as PipelineStage,
      message: result[1] as String?,
    );
  }
}

class LatencyMetrics {
  LatencyMetrics({
    required this.vadMs,
    required this.sttMs,
    required this.translationMs,
    required this.ttsMs,
    required this.totalMs,
  });

  double vadMs;

  double sttMs;

  double translationMs;

  double ttsMs;

  double totalMs;

  Object encode() {
    return <Object?>[
      vadMs,
      sttMs,
      translationMs,
      ttsMs,
      totalMs,
    ];
  }

  static LatencyMetrics decode(Object result) {
    result as List<Object?>;
    return LatencyMetrics(
      vadMs: result[0]! as double,
      sttMs: result[1]! as double,
      translationMs: result[2]! as double,
      ttsMs: result[3]! as double,
      totalMs: result[4]! as double,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PipelineStage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is StatusUpdate) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is LatencyMetrics) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PipelineStage.values[value];
      case 130: 
        return StatusUpdate.decode(readValue(buffer)!);
      case 131: 
        return LatencyMetrics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> Kotlin: commands the Flutter UI sends to the native pipeline.
class EchoEchoHostApi {
  /// Constructor for [EchoEchoHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EchoEchoHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startPipeline(String sourceLanguage, String targetLanguage) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.phase2_mobile.EchoEchoHostApi.startPipeline$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[sourceLanguage, targetLanguage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopPipeline() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.phase2_mobile.EchoEchoHostApi.stopPipeline$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Kotlin -> Dart: events the native pipeline pushes to the Flutter UI.
abstract class EchoEchoFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStatusUpdate(StatusUpdate status);

  void onLatencyUpdate(LatencyMetrics metrics);

  static void setUp(EchoEchoFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onStatusUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onStatusUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final StatusUpdate? arg_status = (args[0] as StatusUpdate?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onStatusUpdate was null, expected non-null StatusUpdate.');
          try {
            api.onStatusUpdate(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onLatencyUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onLatencyUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LatencyMetrics? arg_metrics = (args[0] as LatencyMetrics?);
          assert(arg_metrics != null,
              'Argument for dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onLatencyUpdate was null, expected non-null LatencyMetrics.');
          try {
            api.onLatencyUpdate(arg_metrics!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
