// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.echoecho.phase2_mobile.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Pipeline lifecycle stages surfaced to the UI. */
enum class PipelineStage(val raw: Int) {
  IDLE(0),
  LISTENING(1),
  PROCESSING(2),
  SPEAKING(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): PipelineStage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StatusUpdate (
  val stage: PipelineStage,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatusUpdate {
      val stage = pigeonVar_list[0] as PipelineStage
      val message = pigeonVar_list[1] as String?
      return StatusUpdate(stage, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      stage,
      message,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LatencyMetrics (
  val vadMs: Double,
  val sttMs: Double,
  val translationMs: Double,
  val ttsMs: Double,
  val totalMs: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LatencyMetrics {
      val vadMs = pigeonVar_list[0] as Double
      val sttMs = pigeonVar_list[1] as Double
      val translationMs = pigeonVar_list[2] as Double
      val ttsMs = pigeonVar_list[3] as Double
      val totalMs = pigeonVar_list[4] as Double
      return LatencyMetrics(vadMs, sttMs, translationMs, ttsMs, totalMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vadMs,
      sttMs,
      translationMs,
      ttsMs,
      totalMs,
    )
  }
}
private open class EchoEchoApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PipelineStage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatusUpdate.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LatencyMetrics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PipelineStage -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is StatusUpdate -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LatencyMetrics -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart -> Kotlin: commands the Flutter UI sends to the native pipeline.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface EchoEchoHostApi {
  fun startPipeline(sourceLanguage: String, targetLanguage: String)
  fun stopPipeline()

  companion object {
    /** The codec used by EchoEchoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EchoEchoApiPigeonCodec()
    }
    /** Sets up an instance of `EchoEchoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EchoEchoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase2_mobile.EchoEchoHostApi.startPipeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceLanguageArg = args[0] as String
            val targetLanguageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.startPipeline(sourceLanguageArg, targetLanguageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phase2_mobile.EchoEchoHostApi.stopPipeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopPipeline()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Kotlin -> Dart: events the native pipeline pushes to the Flutter UI.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class EchoEchoFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EchoEchoFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      EchoEchoApiPigeonCodec()
    }
  }
  fun onStatusUpdate(statusArg: StatusUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onStatusUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onLatencyUpdate(metricsArg: LatencyMetrics, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.phase2_mobile.EchoEchoFlutterApi.onLatencyUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(metricsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
